<?php
/**
 * Created by PhpStorm.
 * User: Du
 * Date: 17/10/7
 * Time: 下午2:55
 */

namespace app\models;


use yii\db\ActiveRecord;

class Test extends ActiveRecord{

    public static function tableName()
    {
        return "user"; // TODO: Change the autogenerated stub
    }

}